global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - 'localhost:9090'

  - job_name: 'grafana'
    static_configs:
      - targets: 
        - 'grafana:3000'

  - job_name: celery
    static_configs:
      - targets:
        - celery_exporter:9808

  - job_name: node_exporter
    static_configs:
      - targets:
        - node_exporter:9100

  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080
