{
 "title": "Celery / Tasks",
 "description": "A dashboard that monitors Celery. It is created using the Celery-mixin for the the [Celery-exporter](https://github.com/danihodovic/celery-exporter)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "task",
    "query": {
     "query": "label_values(celery_task_received_created, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Celery Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(celery_worker_up)" }
   ]
  },
  {
   "title": "Tasks Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(celery_worker_tasks_active)"
    }
   ]
  },
  {
   "title": "Tasks received by workers last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(celery_task_received_total{job=\"celery\"}[1d]))\n"
    }
   ]
  },
  {
   "title": "Successful completion rate last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(celery_task_succeeded_total{job=\"celery\"}[1d]))\n/(sum(increase(celery_task_succeeded_total{job=\"celery\"}[1d]))\n+sum(increase(celery_task_failed_total{job=\"celery\"}[1d]))\n)\n"
    }
   ]
  },
  { "title": "Individual Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Task Stats",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (name) (increase(celery_task_succeeded_total{job=\"celery\", name=~\"$task\"}[$__range]))\n/(sum by (name) (increase(celery_task_succeeded_total{job=\"celery\", name=~\"$task\"}[$__range]))\n+sum by (name) (increase(celery_task_failed_total{job=\"celery\", name=~\"$task\"}[$__range]))\n)\n"
    },
    {
     "expr": "sum by (name) (increase(celery_task_received_total{job=\"celery\", name=~\"$task\"}[$__range]))\n"
    },
    {
     "expr": "sum by (name) (increase(celery_task_succeeded_total{job=\"celery\", name=~\"$task\"}[$__range]))\n"
    },
    {
     "expr": "sum by (name) (increase(celery_task_failed_total{job=\"celery\", name=~\"$task\"}[$__range]))\n"
    },
    {
     "expr": "sum by (name) (increase(celery_task_rejected_total{job=\"celery\", name=~\"$task\"}[$__range]))\n"
    },
    {
     "expr": "sum by (name) (increase(celery_task_retried_total{job=\"celery\", name=~\"$task\"}[$__range]))\n"
    },
    {
     "expr": "sum by (name) (increase(celery_task_revoked_total{job=\"celery\", name=~\"$task\"}[$__range]))\n"
    }
   ]
  },
  {
   "title": "Tasks completed with 1m intervals",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (increase(celery_task_succeeded_total{job=\"celery\", name=~\"$task\"}[1m]))\n",
     "legendFormat": "Succeeded - {{ name }}"
    },
    {
     "expr": "sum by (name) (increase(celery_task_failed_total{job=\"celery\", name=~\"$task\"}[1m]))\n",
     "legendFormat": "Failed - {{ name }}"
    },
    {
     "expr": "sum by (name) (increase(celery_task_retried_total{job=\"celery\", name=~\"$task\"}[1m]))\n",
     "legendFormat": "Retried - {{ name }}"
    },
    {
     "expr": "sum by (name) (increase(celery_task_rejected_total{job=\"celery\", name=~\"$task\"}[1m]))\n",
     "legendFormat": "Rejected - {{ name }}"
    },
    {
     "expr": "sum by (name) (increase(celery_task_revoked_total{job=\"celery\", name=~\"$task\"}[1m]))\n",
     "legendFormat": "Revoked - {{ name }}"
    }
   ]
  }
 ]
}