{
 "title": "Thesis Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "query_result(node_exporter_build_info OR cadvisor_version_info)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "query_result(node_exporter_build_info{job=~\"$job\"} OR cadvisor_version_info{job=~\"$job\"})"
    }
   },
   {
    "name": "task",
    "label": "Task",
    "query": {
     "query": "label_values(celery_task_received_created, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System's Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30s])) * 100)"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}-(node_memory_Buffers_bytes{instance=~\"$node\"}+node_memory_Cached_bytes{instance=~\"$node\"}+node_memory_MemFree_bytes{instance=~\"$node\"})",
     "legendFormat": "Used memory"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\",instance=~\"$node\"}[30s])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\",instance=~\"$node\"}[30s])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total{instance=~\"$node\"}[30s])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$node\"}[30s])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  { "title": "Docker Containers' Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",instance=~\"$node\"}[30s])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\",instance=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name!=\"\",instance=~\"$node\"}[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name!=\"\",instance=~\"$node\"}[30s])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Celery's Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Tasks completed with 1m intervals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (increase(celery_task_succeeded_total{job=\"celery\", name=~\"$task\"}[1m]))\n",
     "legendFormat": "Succeeded - {{ name }}"
    },
    {
     "expr": "sum by (name) (increase(celery_task_failed_total{job=\"celery\", name=~\"$task\"}[1m]))\n",
     "legendFormat": "Failed - {{ name }}"
    },
    {
     "expr": "sum by (name) (increase(celery_task_retried_total{job=\"celery\", name=~\"$task\"}[1m]))\n",
     "legendFormat": "Retried - {{ name }}"
    },
    {
     "expr": "sum by (name) (increase(celery_task_rejected_total{job=\"celery\", name=~\"$task\"}[1m]))\n",
     "legendFormat": "Rejected - {{ name }}"
    },
    {
     "expr": "sum by (name) (increase(celery_task_revoked_total{job=\"celery\", name=~\"$task\"}[1m]))\n",
     "legendFormat": "Revoked - {{ name }}"
    }
   ]
  }
 ]
}